### PR TITLE
worker compatibility

### PR DESCRIPTION
**Pull request by mpfau**
see #132

### CODE REVIEW

**Comment by alexisvincent** [comment]
Awesome :) Can you make the `isWorker` and `isWeb` constants?

**Comment by mpfau** [comment]
sure! :+1:

**Comment by alexisvincent** [comment]
Awesome :) Can you give a short description of what is now working? So I can add to the README

**Comment by alexisvincent** [comment]
@mpfau Did you test this, because I just ran rollup and it complained. Which leads me to suspect you never checked if these changes work...

**Comment by mpfau** [comment]
@alexisvincent argh! Sorry! I tested the code but made some slight adaptions before checking in.

The latest commit also contains a fix in case entries are not provided.

**Pull request merged**
